local cfg = {}

cfg.items = {
	-- GERAIS
	["identidade"] = { index = "identidade", nome = "Identidade", type = "usar", peso = 0.1 },

	["colete"] = { index = "colete", nome = "Colete", type = "usar", peso = 3.0 },

	["cartaodedebito"] = { index = "cartaodedebito", nome = "Cartão de Débito", type = "usar", peso = 0.1 }, 

	["cartaodecredito"] = { index = "cartaodecredito", nome = "Cartão de Crédito", type = "usar", peso = 0.1 },

	["maquininha"] = { index = "maquininha", nome = "Maquininha", type = "usar", peso = 0.5 },

	-- ILEGAL
	["dinheirosujo"] = { index = "dinheirosujo", nome = "Dinheiro Sujo", type = "usar", peso = 0.0 },

	["maconha"] = { index = "maconha", nome = "Maconha", type = "usar", peso = 0.2 },
	["adubo"] = { index = "adubo", nome = "Adubo", type = "usar", peso = 0.2 },
	["fertilizante"] = { index = "fertilizante", nome = "Fertilizante", type = "usar", peso = 0.2 },
	["heroina"] = { index = "heroina", nome = "Heroina", type = "usar", peso = 0.2 },
	["cloroformio"] = { index = "cloroformio", nome = "Cloroformio", type = "usar", peso = 0.3 },
	["cocaina"] = { index = "cocaina", nome = "Cocaína", type = "usar", peso = 0.2 },
	["folhadecoca"] = { index = "folhadecoca", nome = "Folha de Coca", type = "usar", peso = 0.2 },
	["pastadecoca"] = { index = "pastadecoca", nome = "Pasta de Coca", type = "usar", peso = 0.2 },
	["lsd"] = { index = "lsd", nome = "LSD", type = "usar", peso = 0.2 },
	["fungo"] = { index = "fungo", nome = "Fungo", type = "usar", peso = 0.2 },
    ["dietilamina"] = { index = "dietilamina", nome = "Dietilamina", type = "usar", peso = 0.2 },
	["metanfetamina"] = { index = "metanfetamina", nome = "Metanfetamina", type = "usar", peso = 0.2 },
	["acidobateria"] = { index = "acidobateria", nome = "Ácido de Bateria", type = "usar", peso = 0.2 },
	["anfetamina"] = { index = "anfetamina", nome = "Anfetamina", type = "usar", peso = 0.2 },

	["armacaodearma"] = { index = "armacaodearma", nome = "Armação de Arma", type = "usar", peso = 0.5 },
	["pecadearma"] = { index = "pecadearma", nome = "Peça de Arma", type = "usar", peso = 0.5 },
	
	["logsinvasao"] = { index = "logsinvasao", nome = "L. Inv. Banco", type = "usar", peso = 0.1 },
	["keysinvasao"] = { index = "keysinvasao", nome = "K. Inv. Banco", type = "usar", peso = 0.1 },

	["capsula"] = { index = "capsula", nome = "Cápsula", type = "usar", peso = 0.2 },
	["polvora"] = { index = "polvora", nome = "Pólvora", type = "usar", peso = 0.1 },

	["placa"] = { index = "placa", nome = "Placa", type = "usar", peso = 0.2 },
	["algemas"] = { index = "algemas", nome = "Algemas", type = "usar", peso = 0.3 },
	["capuz"] = { index = "capuz", nome = "Capuz", type = "usar", peso = 0.1 },
	["lockpick"] = { index = "lockpick", nome = "Lockpick", type = "usar", peso = 0.1 },
	["masterpick"] = { index = "masterpick", nome = "Masterpick", type = "usar", peso = 0.2 },
	["militec"] = { index = "militec", nome = "Militec-1", type = "usar", peso = 0.5 },
	["pendrive"] = { index = "pendrive", nome = "Pendrive", type = "usar", peso = 0.1 },

	["relogioroubado"] = { index = "relogioroubado", nome = "Relógio Roubado", type = "usar", peso = 0.2 },
	["pulseiraroubada"] = { index = "pulseiraroubada", nome = "Pulseira Roubada", type = "usar", peso = 0.2 },
	["anelroubado"] = { index = "anelroubado", nome = "Anel Roubado", type = "usar", peso = 0.2 },
	["colarroubado"] = { index = "colarroubado", nome = "Colar Roubado", type = "usar", peso = 0.2 },
	["brincoroubado"] = { index = "brincoroubado", nome = "Brinco Roubado", type = "usar", peso = 0.2 },
	["carteiraroubada"] = { index = "carteiraroubada", nome = "Carteira Roubada", type = "usar", peso = 0.2 },
	["cartaoclonado"] = { index = "cartaoclonado", nome = "Cartão Clonado", type = "usar", peso = 0.2 },
	["tabletroubado"] = { index = "tabletroubado", nome = "Tablet Roubado", type = "usar", peso = 0.2 },
	["sapatosroubado"] = { index = "sapatosroubado", nome = "Sapatos Roubados", type = "usar", peso = 0.2 },

	["c4"] = { index = "c4", nome = "C4", type = "usar", peso = 3.0 },
	["furadeira"] = { index = "furadeira", nome = "Furadeira", type = "usar", peso = 3.0 },
	["serra"] = { index = "serra", nome = "Serra", type = "usar", peso = 2.0 },

	-- VIP
	["valefone"] = { index = "valefone", nome = "Vale Troca Número", type = "usar", peso = 0.0 },
	["valeplaca"] = { index = "valeplaca", nome = "Vale Troca Placa", type = "usar", peso = 0.0 },
	["valemansao"] = { index = "valemansao", nome = "Vale Mansão", type = "usar", peso = 0.0 },
	["valegaragem"] = { index = "valegaragem", nome = "Vale +1 Garagem", type = "usar", peso = 0.0 },
	
	-- LOJINHA
	["ferramenta"] = { index = "ferramenta", nome = "Ferramenta", type = "usar", peso = 1.0 },
	["celular"] = { index = "celular", nome = "Celular", type = "usar", peso = 0.1 },
	["repairkit"] = { index = "repairkit", nome = "Kit de Reparos", type = "usar", peso = 5.0 },
	["pneus"] = { index = "pneus", nome = "Pneus", type = "usar", peso = 5.0 },
	["energetico"] = { index = "energetico", nome = "Energético", type = "usar", peso = 0.2 },
	["mochila"] = { index = "mochila", nome = "Mochila", type = "usar", peso = 0.3 },
	["radio"] = { index = "radio", nome = "Radio", type = "usar", peso = 0.6 },
	["roupas"] = { index = "roupas", nome = "Roupas", type = "usar", peso = 1.0 },
	["aneldecompromisso"] = { index = "aneldecompromisso", nome = "Anel de Compromisso", type = "usar", peso = 0.0 },
	["alianca"] = { index = "alianca", nome = "Aliança", type = "usar", peso = 0.0 },
	["buque"] = { index = "buque", nome = "Buquê de Flores", type = "usar", peso = 0.4 },

	-- ITENS MÉDICOS
	["omeprazol"] = { index = "omeprazol", nome = "Omeprazol", type = "usar", peso = 0.5 },
	["dipirona"] = { index = "dipirona", nome = "Dipirona", type = "usar", peso = 0.5 },
	["paracetamol"] = { index = "paracetamol", nome = "Paracetamol", type = "usar", peso = 0.5 },
	["decupramim"] = { index = "decupramim", nome = "Decupramim", type = "usar", peso = 0.5 },
	["buscopan"] = { index = "buscopan", nome = "Buscopan", type = "usar", peso = 0.5 },
	["novalgina"] = { index = "novalgina", nome = "Novalgina", type = "usar", peso = 0.5 },
	["alivium"] = { index = "alivium", nome = "Alivium", type = "usar", peso = 0.5 },
	["nokusin"] = { index = "nokusin", nome = "Nokusin", type = "usar", peso = 0.5 },
	["sidelnafila"] = { index = "sidelnafila", nome = "Sidelnafila", type = "usar", peso = 0.5 },
	["bandagem"] = { index = "bandagem", nome = "Bandagem", type = "usar", peso = 0.5 },
	["morfina"] = { index = "morfina", nome = "Morfina", type = "usar", peso = 0.5 },

	-- EMPREGO
	["encomenda"] = { index = "encomenda", nome = "Encomenda", type = "usar", peso = 1.0 },
	["caixa-vazia"] = { index = "caixa-vazia", nome = "Caixa Vazia", type = "usar", peso = 0.0 },
	["garrafadeleite"] = { index = "garrafadeleite", nome = "Garrafa de Leite", type = "usar", peso = 1.0 },
	["garrafavazia"] = { index = "garrafavazia", nome = "Garrafa Vazia", type = "usar", peso = 0.0 },
	["receita-medica"] = { index = "receita-medica", nome = "Receita Médica", type = "usar", peso = 0.0 },
	["tora"] = { index = "tora", nome = "Tora de Madeira", type = "usar", peso = 0.6 },
	["plastico"] = { index = "plastico", nome = "Plástico", type = "usar", peso = 0.0 },
	["graos"] = { index = "graos", nome = "Graos", type = "usar", peso = 0.2 },
	["graosimpuros"] = { index = "graosimpuros", nome = "Graos Impuros", type = "usar", peso = 0.4 },

	-- Burguershot
	["bebidas"] = { index = "bebidas", nome = "Bebidas Burguershot", type = "usar", peso = 0.5 },
	["ingredientes"] = { index = "indredientes", nome = "Indredientes Burguershot", type = "usar", peso = 0.5 },
	["lanche"] = { index = "lanche", nome = "Lanche Burguershot", type = "usar", peso = 0.3 },
	["coxadefrango"] = { index = "coxadefrango", nome = "Coxa de Frango", type = "usar", peso = 0.2  },
	["hamburguer"] = { index = "hamburguer", nome = "Hamburguer", type = "usar", peso = 0.2 },

	["carnedecormorao"] = { index = "carnedecormorao", nome = "Carne de Cormorão", type = "usar", peso = 0.3 },
	["carnedecorvo"] = { index = "carnedecorvo", nome = "Carne de Corvo", type = "usar", peso = 0.3 },
	["carnedeaguia"] = { index = "carnedeaguia", nome = "Carne de Águia", type = "usar", peso = 0.3 },
	["carnedecervo"] = { index = "carnedecervo", nome = "Carne de Cervo", type = "usar", peso = 0.3 },
	["carnedecoelho"] = { index = "carnedecoelho", nome = "Carne de Coelho", type = "usar", peso = 0.3 },
	["carnedecoyote"] = { index = "carnedecoyote", nome = "Carne de Coyote", type = "usar", peso = 0.3 },
	["carnedelobo"] = { index = "carnedelobo", nome = "Carne de Lobo", type = "usar", peso = 0.3 },
	["carnedepuma"] = { index = "carnedepuma", nome = "Carne de Puma", type = "usar", peso = 0.3 },
	["carnedejavali"] = { index = "carnedejavali", nome = "Carne de Javali", type = "usar", peso = 0.3 },

	["isca"] = { index = "isca", nome = "Isca", type = "usar", peso = 0.1 },
	["dourado"] = { index = "dourado", nome = "Dourado", type = "usar", peso = 0.5 },
	["corvina"] = { index = "corvina", nome = "Corvina", type = "usar", peso = 0.5 },
	["salmao"] = { index = "salmao", nome = "Salmão", type = "usar", peso = 0.5 },
	["pacu"] = { index = "pacu", nome = "Pacu", type = "usar", peso = 0.5 },
	["pintado"] = { index = "pintado", nome = "Pintado", type = "usar", peso = 0.5 },
	["pirarucu"] = { index = "pirarucu", nome = "Pirarucu", type = "usar", peso = 0.5 },
	["tilapia"] = { index = "tilapia", nome = "Tilápia", type = "usar", peso = 0.5 },
	["tucunare"] = { index = "tucunare", nome = "Tucunaré", type = "usar", peso = 0.5 },
	["lambari"] = { index = "lambari", nome = "Lambari", type = "usar", peso = 0.5 },

	["diamante"] = { index = "diamante", nome = "Min. Diamante", type = "usar", peso = 0.3 },
	["ouro"] = { index = "ouro", nome = "Min. Ouro", type = "usar", peso = 0.3 },
	["bronze"] = { index = "bronze", nome = "Min. Bronze", type = "usar", peso = 0.3 },
	["ferro"] = { index = "ferro", nome = "Min. Ferro", type = "usar", peso = 0.3 },
	["rubi"] = { index = "rubi", nome = "Min. Rubi", type = "usar", peso = 0.3 },
	["esmeralda"] = { index = "esmeralda", nome = "Min. Esmeralda", type = "usar", peso = 0.3 },
	["safira"] = { index = "safira", nome = "Min. Safira", type = "usar", peso = 0.3 },
	["topazio"] = { index = "topazio", nome = "Min. Topazio", type = "usar", peso = 0.3 },
	["ametista"] = { index = "ametista", nome = "Min. Ametista", type = "usar", peso = 0.3 },

	["diamante2"] = { index = "diamante2", nome = "Diamante", type = "usar", peso = 0.2 },
	["ouro2"] = { index = "ouro2", nome = "Ouro", type = "usar", peso = 0.2 },
	["bronze2"] = { index = "bronze2", nome = "Bronze", type = "usar", peso = 0.2 },
	["ferro2"] = { index = "ferro2", nome = "Ferro", type = "usar", peso = 0.2 },
	["rubi2"] = { index = "rubi2", nome = "Rubi", type = "usar", peso = 0.2 },
	["esmeralda2"] = { index = "esmeralda2", nome = "Esmeralda", type = "usar", peso = 0.2 },
	["safira2"] = { index = "safira2", nome = "Safira", type = "usar", peso = 0.2 },
	["topazio2"] = { index = "topazio2", nome = "Topazio", type = "usar", peso = 0.2 },
	["ametista2"] = { index = "ametista2", nome = "Ametista", type = "usar", peso = 0.2 },

	-- COMIDA
	["laranja"] = { index = "laranja", nome = "Laranja", type = "usar", peso = 0.2 },
	["sanduiche"] = { index = "sanduiche", nome = "Sanduíche", type = "usar", peso = 0.3 },
	["rosquinha"] = { index = "rosquinha", nome = "Rosquinha", type = "usar", peso = 0.1 },
	["hotdog"] = { index = "hotdog", nome = "HotDog", type = "usar", peso = 0.3 },
	["xburguer"] = { index = "xburguer", nome = "xBurguer", type = "usar", peso = 0.4 },
	["chips"] = { index = "chips", nome = "Batata Chips", type = "usar", peso = 0.1 },
	["batataf"] = { index = "batataf", nome = "Batata Frita", type = "usar", peso = 0.3 },
	["pizza"] = { index = "pizza", nome = "Pedaço de Pizza", type = "usar", peso = 0.5 },
	["frango"] = { index = "frango", nome = "Frango Frito", type = "usar", peso = 0.4 },
	["bcereal"] = { index = "bcereal", nome = "Barra de Cereal", type = "usar", peso = 0.1 },
	["bchocolate"] = { index = "bchocolate", nome = "Barra de Chocolate", type = "usar", peso = 0.1 },
	["taco"] = { index = "taco", nome = "Taco", type = "usar", peso = 0.2 },

	-- BEBIDAS
	["cerveja"] = { index = "cerveja", nome = "Cerveja", type = "usar", peso = 0.8 },
	["tequila"] = { index = "tequila", nome = "Tequila", type = "usar", peso = 1.0 },
	["vodka"] = { index = "vodka", nome = "Vodka", type = "usar", peso = 1.0 },
	["whisky"] = { index = "whisky", nome = "Whisky", type = "usar", peso = 1.0 },
	["conhaque"] = { index = "conhaque", nome = "Conhaque", type = "usar", peso = 1.0 },
	["absinto"] = { index = "absinto", nome = "Absinto", type = "usar", peso = 1.0 },

	["agua"] = { index = "agua", nome = "Água", type = "usar", peso = 0.5 },
	["leite"] = { index = "leite", nome = "Leite", type = "usar", peso = 1.0 },
	["cafe"] = { index = "cafe", nome = "Café", type = "usar", peso = 0.2 },
	["cafecleite"] = { index = "cafecleite", nome = "Café com Leite", type = "usar", peso = 0.3 },
	["cafeexpresso"] = { index = "cafeexpresso", nome = "Café Expresso", type = "usar", peso = 0.3 },
	["capuccino"] = { index = "capuccino", nome = "Capuccino", type = "usar", peso = 0.4 },
	["frappuccino"] = { index = "frappuccino", nome = "Frapuccino", type = "usar", peso = 0.3 },
	["cha"] = { index = "cha", nome = "Chá", type = "usar", peso = 0.2 },
	["icecha"] = { index = "icecha", nome = "Chá Gelado", type = "usar", peso = 0.2 },
	["sprunk"] = { index = "sprunk", nome = "Sprunk", type = "usar", peso = 0.4 },
	["cola"] = { index = "cola", nome = "Cola", type = "usar", peso = 0.4 },
	
	-- [ARMAS BRANCAS] ---------------------------------------------
	["wbodyWEAPON_DAGGER"] = { index = "adaga", nome = "Adaga", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_BAT"] = { index = "beisebol", nome = "Taco de Beisebol", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_BOTTLE"] = { index = "garrafa", nome = "Garrafa", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_CROWBAR"] = { index = "cabra", nome = "Pé de Cabra", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_FLASHLIGHT"] = { index = "lanterna", nome = "Lanterna", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_GOLFCLUB"] = { index = "golf", nome = "Taco de Golf", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_HAMMER"] = { index = "martelo", nome = "Martelo", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_HATCHET"] = { index = "machado", nome = "Machado", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_KNUCKLE"] = { index = "ingles", nome = "Soco-Inglês", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_KNIFE"] = { index = "faca", nome = "Faca", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_MACHETE"] = { index = "machete", nome = "Machete", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_SWITCHBLADE"] = { index = "canivete", nome = "Canivete", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_NIGHTSTICK"] = { index = "cassetete", nome = "Cassetete", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_WRENCH"] = { index = "grifo", nome = "Chave de Grifo", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_BATTLEAXE"] = { index = "batalha", nome = "Machado de Batalha", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_POOLCUE"] = { index = "sinuca", nome = "Taco de Sinuca", type = "equipar", peso = 2.0 },
	["wbodyWEAPON_STONE_HATCHET"] = { index = "pedra", nome = "Machado de Pedra", type = "equipar", peso = 2.0 },
	-- [ARMAS DE FOGO] ---------------------------------------------
	["wbodyWEAPON_PISTOL"] = { index = "m1911", nome = "M1911", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_PISTOL_MK2"] = { index = "fiveseven", nome = "FN Five Seven", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_COMBATPISTOL"] = { index = "glock", nome = "Glock 19", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_STUNGUN"] = { index = "taser", nome = "Taser", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_SNSPISTOL"] = { index = "hkp7m10", nome = "HK P7M10", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_VINTAGEPISTOL"] = { index = "m1922", nome = "M1922", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_REVOLVER"] = { index = "magnum44", nome = "Magnum 44", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_REVOLVER_MK2"] = { index = "magnum357", nome = "Magnum 357", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_MUSKET"] = { index = "winchester22", nome = "Winchester 22", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_FLARE"] = { index = "sinalizador", nome = "Sinalizador", type = "equipar", peso = 5.0 },
	["wbodyGADGET_PARACHUTE"] = { index = "paraquedas", nome = "Paraquedas", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_FIREEXTINGUISHER"] = { index = "extintor", nome = "Extintor", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_MICROSMG"] = { index = "uzi", nome = "Uzi", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_CARBINERIFLE"] = { index = "m4a1", nome = "M4A1", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_ASSAULTSMG"] = { index = "mtar21", nome = "MTAR-21", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_COMBATPDW"] = { index = "sigsauer", nome = "Sig Sauer MPX", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_PUMPSHOTGUN_MK2"] = { index = "remington", nome = "Remington 870", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_CARBINERIFLE_MK2"] = { index = "ia2", nome = "IA2", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_ASSAULTRIFLE"] = { index = "ak103", nome = "AK-103", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_PETROLCAN"] = { index = "gasolina", nome = "Galão de Gasolina", type = "equipar", peso = 5.0 },	
	["wbodyWEAPON_GUSENBERG"] = { index = "thompson", nome = "Thompson", type = "equipar", peso = 5.0 },		
	["wbodyWEAPON_MACHINEPISTOL"] = { index = "tec9", nome = "Tec-9", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_COMPACTRIFLE"] = { index = "aks", nome = "AKS", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_SMG"] = { index = "mpx", nome = "MPX", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_PISTOL50"] = { index = "pistol50", nome = "PISTOL50", type = "equipar", peso = 5.0 },
	["wbodyWEAPON_APPISTOL"] = { index = "appistol", nome = "APPISTOL", type = "equipar", peso = 5.0 },
	-- [MUNIÇÕES] ---------------------------------------------
	["wammoWEAPON_PISTOL50"] = { index = "m-pistol50", nome = "M.PISTOL50", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_APPISTOL"] = { index = "m-appistol", nome = "M.APPISTOL", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_PISTOL"] = { index = "m-m1911", nome = "M.M1911", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_PISTOL_MK2"] = { index = "m-fiveseven", nome = "M.FN Five Seven", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_COMBATPISTOL"] = { index = "m-glock", nome = "M.Glock 19", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_STUNGUN"] = { index = "m-taser", nome = "M.Taser", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_SNSPISTOL"] = { index = "m-hkp7m10", nome = "M.HK P7M10", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_VINTAGEPISTOL"] = { index = "m-m1922", nome = "M.M1922", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_REVOLVER"] = { index = "m-magnum44", nome = "M.Magnum 44", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_REVOLVER_MK2"] = { index = "m-magnum357", nome = "M.Magnum 357", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_MUSKET"] = { index = "m-winchester22", nome = "M.Winchester 22", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_FLARE"] = { index = "m-sinalizador", nome = "M.Sinalizador", type = "recarregar", peso = 0.6 },
	["wammoGADGET_PARACHUTE"] = { index = "m-paraquedas", nome = "M.Paraquedas", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_FIREEXTINGUISHER"] = { index = "m-extintor", nome = "M.Extintor", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_MICROSMG"] = { index = "m-uzi", nome = "M.Uzi", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_CARBINERIFLE"] = { index = "m-m4a1", nome = "M.M4A1", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_ASSAULTSMG"] = { index = "m-mtar21", nome = "M.MTAR-21", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_COMBATPDW"] = { index = "m-sigsauer", nome = "M.Sig Sauer MPX", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_PUMPSHOTGUN"] = { index = "m-shotgun", nome = "M.Shotgun", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_PUMPSHOTGUN_MK2"] = { index = "m-remington", nome = "M.Remington 870", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_CARBINERIFLE_MK2"] = { index = "m-ia2", nome = "M.IA2", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_ASSAULTRIFLE"] = { index = "m-ak103", nome = "M.AK-103", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_GUSENBERG"] = { index = "m-thompson", nome = "M.Thompson", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_MACHINEPISTOL"] = { index = "m-tec9", nome = "M.Tec-9", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_COMPACTRIFLE"] = { index = "m-aks", nome = "M.AKS", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_SMG"] = { index = "m-mpx", nome = "M.MPX", type = "recarregar", peso = 0.6 },
	["wammoWEAPON_PETROLCAN"] = { index = "combustivel", nome = "Combustível", type = "recarregar", peso = 0.6 },
}

return cfg