local cfg = {}

cfg.vehicles = {
	--CARROS GTA
	["blista"] = { ['name'] = "Blista", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50 , ["banned"] = false },
	["brioso"] = { ['name'] = "Brioso", ['price'] = 40000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["emperor"] = { ['name'] = "Emperor", ['price'] = 50000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["emperor2"] = { ['name'] = "Emperor 2", ['price'] = 50000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["dilettante"] = { ['name'] = "Dilettante", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["issi2"] = { ['name'] = "Issi2", ['price'] = 200000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["panto"] = { ['name'] = "Panto", ['price'] = 8000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["prairie"] = { ['name'] = "Prairie", ['price'] = 1000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["rhapsody"] = { ['name'] = "Rhapsody", ['price'] = 10000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["cogcabrio"] = { ['name'] = "Cogcabrio", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["exemplar"] = { ['name'] = "Exemplar", ['price'] = 80000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["f620"] = { ['name'] = "F620", ['price'] = 55000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["felon"] = { ['name'] = "Felon", ['price'] = 70000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["ingot"] = { ['name'] = "Ingot", ['price'] = 160000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["jackal"] = { ['name'] = "Jackal", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["oracle"] = { ['name'] = "Oracle", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["oracle2"] = { ['name'] = "Oracle2", ['price'] = 80000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sentinel"] = { ['name'] = "Sentinel", ['price'] = 50000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sentinel2"] = { ['name'] = "Sentinel2", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["windsor"] = { ['name'] = "Windsor", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["windsor2"] = { ['name'] = "Windsor2", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["zion"] = { ['name'] = "Zion", ['price'] = 50000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["zion2"] = { ['name'] = "Zion2", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["blade"] = { ['name'] = "Blade", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["buccaneer"] = { ['name'] = "Buccaneer", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["buccaneer2"] = { ['name'] = "Buccaneer2", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["primo"] = { ['name'] = "Primo", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["chino"] = { ['name'] = "Chino", ['price'] = 100000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["coquette3"] = { ['name'] = "Coquette3", ['price'] = 195000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["dukes"] = { ['name'] = "Dukes", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["faction"] = { ['name'] = "Faction", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["faction3"] = { ['name'] = "Faction3", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["gauntlet"] = { ['name'] = "Gauntlet", ['price'] = 165000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["gauntlet2"] = { ['name'] = "Gauntlet2", ['price'] = 165000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["hermes"] = { ['name'] = "Hermes", ['price'] = 280000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["hotknife"] = { ['name'] = "Hotknife", ['price'] = 180000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["moonbeam"] = { ['name'] = "Moonbeam", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["moonbeam2"] = { ['name'] = "Moonbeam2", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["nightshade"] = { ['name'] = "Nightshade", ['price'] = 270000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["picador"] = { ['name'] = "Picador", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["ruiner"] = { ['name'] = "Ruiner", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sabregt"] = { ['name'] = "Sabregt", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sabregt2"] = { ['name'] = "Sabregt2", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["slamvan"] = { ['name'] = "Slamvan", ['price'] = 180000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["slamvan3"] = { ['name'] = "Slamvan3", ['price'] = 230000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["stalion"] = { ['name'] = "Stalion", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["stalion2"] = { ['name'] = "Stalion2", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["tampa"] = { ['name'] = "Tampa", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["vigero"] = { ['name'] = "Vigero", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["virgo"] = { ['name'] = "Virgo", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["virgo2"] = { ['name'] = "Virgo2", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["virgo3"] = { ['name'] = "Virgo3", ['price'] = 180000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["voodoo"] = { ['name'] = "Voodoo", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["voodoo2"] = { ['name'] = "Voodoo2", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["yosemite"] = { ['name'] = "Yosemite", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["bfinjection"] = { ['name'] = "Bfinjection", ['price'] = 80000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["bifta"] = { ['name'] = "Bifta", ['price'] = 190000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["bodhi2"] = { ['name'] = "Bodhi2", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["brawler"] = { ['name'] = "Brawler", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["trophytruck"] = { ['name'] = "Trophytruck", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["trophytruck2"] = { ['name'] = "Trophytruck2", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["dubsta3"] = { ['name'] = "Dubsta3", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["mesa3"] = { ['name'] = "Mesa3", ['price'] = 200000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["rancherxl"] = { ['name'] = "Rancherxl", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["rebel2"] = { ['name'] = "Rebel2", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["riata"] = { ['name'] = "Riata", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["dloader"] = { ['name'] = "Dloader", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["sandking"] = { ['name'] = "Sandking", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["sandking2"] = { ['name'] = "Sandking2", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["baller"] = { ['name'] = "Baller", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["baller2"] = { ['name'] = "Baller2", ['price'] = 160000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["baller3"] = { ['name'] = "Baller3", ['price'] = 175000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["baller4"] = { ['name'] = "Baller4", ['price'] = 185000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["baller5"] = { ['name'] = "Baller5", ['price'] = 270000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["baller6"] = { ['name'] = "Baller6", ['price'] = 280000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["bjxl"] = { ['name'] = "Bjxl", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["cavalcade"] = { ['name'] = "Cavalcade", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["cavalcade2"] = { ['name'] = "Cavalcade2", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["contender"] = { ['name'] = "Contender", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["dubsta"] = { ['name'] = "Dubsta", ['price'] = 210000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["dubsta2"] = { ['name'] = "Dubsta2", ['price'] = 240000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["fq2"] = { ['name'] = "Fq2", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["granger"] = { ['name'] = "Granger", ['price'] = 345000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["gresley"] = { ['name'] = "Gresley", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["habanero"] = { ['name'] = "Habanero", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["seminole"] = { ['name'] = "Seminole", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["serrano"] = { ['name'] = "Serrano", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["xls"] = { ['name'] = "Xls", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["xls2"] = { ['name'] = "Xls2", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["asea"] = { ['name'] = "Asea", ['price'] = 55000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["asterope"] = { ['name'] = "Asterope", ['price'] = 65000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["cog552"] = { ['name'] = "Cog552", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["cognoscenti"] = { ['name'] = "Cognoscenti", ['price'] = 280000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["cognoscenti2"] = { ['name'] = "Cognoscenti2", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["stanier"] = { ['name'] = "Stanier", ['price'] = 105000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["stratum"] = { ['name'] = "Stratum", ['price'] = 90000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["surge"] = { ['name'] = "Surge", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["tailgater"] = { ['name'] = "Tailgater", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["warrener"] = { ['name'] = "Warrener", ['price'] = 90000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["washington"] = { ['name'] = "Washington", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["alpha"] = { ['name'] = "Alpha", ['price'] = 230000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["banshee"] = { ['name'] = "Banshee", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["bestiagts"] = { ['name'] = "Bestiagts", ['price'] = 290000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["blista2"] = { ['name'] = "Blista2", ['price'] = 55000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["blista3"] = { ['name'] = "Blista3", ['price'] = 80000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["buffalo"] = { ['name'] = "Buffalo", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["buffalo2"] = { ['name'] = "Buffalo2", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["buffalo3"] = { ['name'] = "Buffalo3", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["carbonizzare"] = { ['name'] = "Carbonizzare", ['price'] = 290000, ['tipo'] = "esportivos", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["comet2"] = { ['name'] = "Comet2", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["comet3"] = { ['name'] = "Comet3", ['price'] = 290000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["comet5"] = { ['name'] = "Comet5", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["coquette"] = { ['name'] = "Coquette", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["elegy"] = { ['name'] = "Elegy", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["elegy2"] = { ['name'] = "Elegy2", ['price'] = 355000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["feltzer2"] = { ['name'] = "Feltzer2", ['price'] = 255000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["furoregt"] = { ['name'] = "Furoregt", ['price'] = 290000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["fusilade"] = { ['name'] = "Fusilade", ['price'] = 210000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["futo"] = { ['name'] = "Futo", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["jester"] = { ['name'] = "Jester", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["khamelion"] = { ['name'] = "Khamelion", ['price'] = 210000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["kuruma"] = { ['name'] = "Kuruma", ['price'] = 330000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["massacro"] = { ['name'] = "Massacro", ['price'] = 330000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["massacro2"] = { ['name'] = "Massacro2", ['price'] = 330000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["ninef"] = { ['name'] = "Ninef", ['price'] = 290000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["ninef2"] = { ['name'] = "Ninef2", ['price'] = 290000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["omnis"] = { ['name'] = "Omnis", ['price'] = 240000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["pariah"] = { ['name'] = "Pariah", ['price'] = 500000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["penumbra"] = { ['name'] = "Penumbra", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["raiden"] = { ['name'] = "Raiden", ['price'] = 240000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["rapidgt"] = { ['name'] = "Rapidgt", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["rapidgt2"] = { ['name'] = "Rapidgt2", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["ruston"] = { ['name'] = "Ruston", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["schafter3"] = { ['name'] = "Schafter3", ['price'] = 275000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["schafter2"] = { ['name'] = "schafter2", ['price'] = 45000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["schafter4"] = { ['name'] = "Schafter4", ['price'] = 420000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["schafter5"] = { ['name'] = "Schafter5", ['price'] = 275000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["schwarzer"] = { ['name'] = "Schwarzer", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sentinel3"] = { ['name'] = "Sentinel3", ['price'] = 230000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["seven70"] = { ['name'] = "Seven70", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["specter"] = { ['name'] = "Specter", ['price'] = 320000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["specter2"] = { ['name'] = "Specter2", ['price'] = 355000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["streiter"] = { ['name'] = "Streiter", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["sultan"] = { ['name'] = "Sultan", ['price'] = 210000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["surano"] = { ['name'] = "Surano", ['price'] = 310000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["tampa2"] = { ['name'] = "Tampa2", ['price'] = 200000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["tropos"] = { ['name'] = "Tropos", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["verlierer2"] = { ['name'] = "Verlierer2", ['price'] = 380000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["btype2"] = { ['name'] = "Btype2", ['price'] = 460000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["btype3"] = { ['name'] = "Btype3", ['price'] = 390000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["casco"] = { ['name'] = "Casco", ['price'] = 355000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["cheetah"] = { ['name'] = "Cheetah", ['price'] = 425000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["coquette2"] = { ['name'] = "Coquette2", ['price'] = 285000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["feltzer3"] = { ['name'] = "Feltzer3", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["gt500"] = { ['name'] = "Gt500", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["infernus2"] = { ['name'] = "Infernus2", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["jb700"] = { ['name'] = "Jb700", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["mamba"] = { ['name'] = "Mamba", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["manana"] = { ['name'] = "Manana", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["monroe"] = { ['name'] = "Monroe", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["peyote"] = { ['name'] = "Peyote", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["pigalle"] = { ['name'] = "Pigalle", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["rapidgt3"] = { ['name'] = "Rapidgt3", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["retinue"] = { ['name'] = "Retinue", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["stinger"] = { ['name'] = "Stinger", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["stingergt"] = { ['name'] = "Stingergt", ['price'] = 230000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["torero"] = { ['name'] = "Torero", ['price'] = 160000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["tornado"] = { ['name'] = "Tornado", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["tornado2"] = { ['name'] = "Tornado2", ['price'] = 160000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["tornado6"] = { ['name'] = "Tornado6", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["turismo2"] = { ['name'] = "Turismo2", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["ztype"] = { ['name'] = "Ztype", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["adder"] = { ['name'] = "Adder", ['price'] = 620000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["autarch"] = { ['name'] = "Autarch", ['price'] = 760000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["banshee2"] = { ['name'] = "Banshee2", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["bullet"] = { ['name'] = "Bullet", ['price'] = 400000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["cheetah2"] = { ['name'] = "Cheetah2", ['price'] = 240000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["entityxf"] = { ['name'] = "Entityxf", ['price'] = 460000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["fmj"] = { ['name'] = "Fmj", ['price'] = 520000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["gp1"] = { ['name'] = "Gp1", ['price'] = 495000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["infernus"] = { ['name'] = "Infernus", ['price'] = 470000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["nero"] = { ['name'] = "Nero", ['price'] = 450000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["nero2"] = { ['name'] = "Nero2", ['price'] = 480000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["osiris"] = { ['name'] = "Osiris", ['price'] = 460000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["penetrator"] = { ['name'] = "Penetrator", ['price'] = 480000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["pfister811"] = { ['name'] = "Pfister811", ['price'] = 530000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["reaper"] = { ['name'] = "Reaper", ['price'] = 620000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["sc1"] = { ['name'] = "Sc1", ['price'] = 495000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sultanrs"] = { ['name'] = "Sultan RS", ['price'] = 450000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["t20"] = { ['name'] = "T20", ['price'] = 670000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["tempesta"] = { ['name'] = "Tempesta", ['price'] = 600000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["turismor"] = { ['name'] = "Turismor", ['price'] = 620000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["tyrus"] = { ['name'] = "Tyrus", ['price'] = 620000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["vacca"] = { ['name'] = "Vacca", ['price'] = 620000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["visione"] = { ['name'] = "Visione", ['price'] = 690000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["voltic"] = { ['name'] = "Voltic", ['price'] = 440000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["zentorno"] = { ['name'] = "Zentorno", ['price'] = 920000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["sadler"] = { ['name'] = "Sadler", ['price'] = 180000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["bison"] = { ['name'] = "Bison", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["bison2"] = { ['name'] = "Bison2", ['price'] = 180000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["bobcatxl"] = { ['name'] = "Bobcatxl", ['price'] = 260000, ['tipo'] = "import", ['mala'] = 50, ["banned"] = false },
	["burrito"] = { ['name'] = "Burrito", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["burrito2"] = { ['name'] = "Burrito2", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["burrito3"] = { ['name'] = "Burrito3", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["burrito4"] = { ['name'] = "Burrito4", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["mule4"] = { ['name'] = "Burrito4", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["rallytruck"] = { ['name'] = "Burrito4", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["minivan"] = { ['name'] = "Minivan", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["minivan2"] = { ['name'] = "Minivan2", ['price'] = 220000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["pony"] = { ['name'] = "Pony", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["pony2"] = { ['name'] = "Pony2", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["rumpo"] = { ['name'] = "Rumpo", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["rumpo2"] = { ['name'] = "Rumpo2", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["rumpo3"] = { ['name'] = "Rumpo3", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["surfer"] = { ['name'] = "Surfer", ['price'] = 55000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["youga"] = { ['name'] = "Youga", ['price'] = 260000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["huntley"] = { ['name'] = "Huntley", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["landstalker"] = { ['name'] = "Landstalker", ['price'] = 130000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["mesa"] = { ['name'] = "Mesa", ['price'] = 90000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["patriot"] = { ['name'] = "Patriot", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["radi"] = { ['name'] = "Radi", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["rocoto"] = { ['name'] = "Rocoto", ['price'] = 110000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["tyrant"] = { ['name'] = "Tyrant", ['price'] = 690000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["entity2"] = { ['name'] = "Entity2", ['price'] = 550000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["cheburek"] = { ['name'] = "Cheburek", ['price'] = 170000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["hotring"] = { ['name'] = "Hotring", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["jester3"] = { ['name'] = "Jester3", ['price'] = 345000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["flashgt"] = { ['name'] = "Flashgt", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["ellie"] = { ['name'] = "Ellie", ['price'] = 320000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["michelli"] = { ['name'] = "Michelli", ['price'] = 160000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["fagaloa"] = { ['name'] = "Fagaloa", ['price'] = 320000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["stromberg"] = { ['name'] = "stromberg", ['price'] = 77000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["dominator"] = { ['name'] = "Dominator", ['price'] = 230000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["dominator2"] = { ['name'] = "Dominator2", ['price'] = 230000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["dominator3"] = { ['name'] = "Dominator3", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["issi3"] = { ['name'] = "Issi3", ['price'] = 190000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["taipan"] = { ['name'] = "Taipan", ['price'] = 620000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["gb200"] = { ['name'] = "Gb200", ['price'] = 195000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["stretch"] = { ['name'] = "Stretch", ['price'] = 520000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["guardian"] = { ['name'] = "Guardian", ['price'] = 540000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["kamacho"] = { ['name'] = "Kamacho", ['price'] = 460000, ['tipo'] = "carros", ['modelo'] = "suv", ['mala'] = 50, ["banned"] = false },
	["neon"] = { ['name'] = "Neon", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["cyclone"] = { ['name'] = "Cyclone", ['price'] = 920000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["italigtb"] = { ['name'] = "Italigtb", ['price'] = 600000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["italigtb2"] = { ['name'] = "Italigtb2", ['price'] = 610000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["vagner"] = { ['name'] = "Vagner", ['price'] = 680000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["xa21"] = { ['name'] = "Xa21", ['price'] = 630000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["tezeract"] = { ['name'] = "Tezeract", ['price'] = 920000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["prototipo"] = { ['name'] = "Prototipo", ['price'] = 1030000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["patriot2"] = { ['name'] = "Patriot2", ['price'] = 550000, ['tipo'] = "carros", ['modelo'] = "outros", ['mala'] = 50, ["banned"] = false },
	["swinger"] = { ['name'] = "Swinger", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["clique"] = { ['name'] = "Clique", ['price'] = 360000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["deveste"] = { ['name'] = "Deveste", ['price'] = 920000, ['tipo'] = "carros", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["deviant"] = { ['name'] = "Deviant", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["impaler"] = { ['name'] = "Impaler", ['price'] = 320000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["italigto"] = { ['name'] = "Italigto", ['price'] = 800000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["schlagen"] = { ['name'] = "Schlagen", ['price'] = 690000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["toros"] = { ['name'] = "Toros", ['price'] = 600000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["tulip"] = { ['name'] = "Tulip", ['price'] = 320000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["vamos"] = { ['name'] = "Vamos", ['price'] = 320000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["freecrawler"] = { ['name'] = "Freecrawler", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["fugitive"] = { ['name'] = "Fugitive", ['price'] = 50000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["glendale"] = { ['name'] = "Glendale", ['price'] = 70000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["intruder"] = { ['name'] = "Intruder", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["le7b"] = { ['name'] = "Le7b", ['price'] = 700000, ['tipo'] = "carros", ['modelo'] = "esportivos", ['mala'] = 50, ["banned"] = false },
	["lurcher"] = { ['name'] = "Lurcher", ['price'] = 150000, ['tipo'] = "carros", ['modelo'] = "antigos", ['mala'] = 50, ["banned"] = false },
	["lynx"] = { ['name'] = "Lynx", ['price'] = 370000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["phoenix"] = { ['name'] = "Phoenix", ['price'] = 250000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["premier"] = { ['name'] = "Premier", ['price'] = 35000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["raptor"] = { ['name'] = "Raptor", ['price'] = 300000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["sheava"] = { ['name'] = "Sheava", ['price'] = 700000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["z190"] = { ['name'] = "Z190", ['price'] = 350000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["camper"] = { ['name'] = "camper", ['price'] = 60000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["journey"] = { ['name'] = "journey", ['price'] = 40000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["ratloader2"] = { ['name'] = "ratloader2", ['price'] = 18000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["regina"] = { ['name'] = "regina", ['price'] = 22500, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["revolter"] = { ['name'] = "revolter", ['price'] = 200000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["savestra"] = { ['name'] = "savestra", ['price'] = 85000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },
	["viseris"] = { ['name'] = "viseris", ['price'] = 200000, ['tipo'] = "carros", ['modelo'] = "carro", ['mala'] = 50, ["banned"] = false },

	--MOTOS GTA
	["akuma"] = { ['name'] = "Akuma", ['price'] = 500000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["avarus"] = { ['name'] = "Avarus", ['price'] = 440000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["bagger"] = { ['name'] = "Bagger", ['price'] = 300000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["bati"] = { ['name'] = "Bati", ['price'] = 370000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["bati2"] = { ['name'] = "Bati2", ['price'] = 300000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["bf400"] = { ['name'] = "Bf400", ['price'] = 320000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["carbonrs"] = { ['name'] = "Carbonrs", ['price'] = 370000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["chimera"] = { ['name'] = "Chimera", ['price'] = 345000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["cliffhanger"] = { ['name'] = "Cliffhanger", ['price'] = 310000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["daemon2"]  = { ['name'] = "Daemon2", ['price'] = 240000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["defiler"] = { ['name'] = "Defiler", ['price'] = 460000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["diablous"] = { ['name'] = "Diablous", ['price'] = 430000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["diablous2"] = { ['name'] = "Diablous2", ['price'] = 460000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["double"] = { ['name'] = "Double", ['price'] = 370000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["enduro"] = { ['name'] = "Enduro", ['price'] = 195000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["esskey"] = { ['name'] = "Esskey", ['price'] = 320000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["faggio"] = { ['name'] = "Faggio", ['price'] = 4000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["faggio2"] = { ['name'] = "Faggio2", ['price'] = 5000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["faggio3"] = { ['name'] = "Faggio3", ['price'] = 5000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["fcr"] = { ['name'] = "Fcr", ['price'] = 390000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["fcr2"] = { ['name'] = "Fcr2", ['price'] = 390000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["gargoyle"] = { ['name'] = "Gargoyle", ['price'] = 345000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["hakuchou"] = { ['name'] = "Hakuchou", ['price'] = 380000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["hakuchou2"] = { ['name'] = "Hakuchou2", ['price'] = 550000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["hexer"] = { ['name'] = "Hexer", ['price'] = 250000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["innovation"] = { ['name'] = "Innovation", ['price'] = 250000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["lectro"] = { ['name'] = "Lectro", ['price'] = 380000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["manchez"] = { ['name'] = "Manchez", ['price'] = 355000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["nemesis"] = { ['name'] = "Nemesis", ['price'] = 345000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["nightblade"] = { ['name'] = "Nightblade", ['price'] = 415000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["pcj"] = { ['name'] = "Pcj", ['price'] = 230000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["ruffian"] = { ['name'] = "Ruffian", ['price'] = 345000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["sanchez"] = { ['name'] = "Sanchez", ['price'] = 185000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["sanchez2"] = { ['name'] = "Sanchez2", ['price'] = 185000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["sovereign"] = { ['name'] = "Sovereign", ['price'] = 285000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["thrust"] = { ['name'] = "Thrust", ['price'] = 375000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["vader"] = { ['name'] = "Vader", ['price'] = 345000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["vindicator"] = { ['name'] = "Vindicator", ['price'] = 340000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["vortex"] = { ['name'] = "Vortex", ['price'] = 375000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["wolfsbane"] = { ['name'] = "Wolfsbane", ['price'] = 290000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["zombiea"] = { ['name'] = "Zombiea", ['price'] = 290000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["zombieb"] = { ['name'] = "Zombieb", ['price'] = 300000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["shotaro"] = { ['name'] = "Shotaro", ['price'] = 1000000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["ratbike"] = { ['name'] = "Ratbike", ['price'] = 230000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["blazer"] = { ['name'] = "Blazer", ['price'] = 230000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },
	["blazer4"] = { ['name'] = "Blazer4", ['price'] = 370000, ['tipo'] = "motos", ['modelo'] = "moto", ['mala'] = 25, ["banned"] = false },

	--TRABALHO
	["youga2"] = { ['name'] = "Youga2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["felon2"] = { ['name'] = "Felon2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["pbus"] = { ['name'] = "PBus", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiacharger2018"] = { ['name'] = "Dodge Charger 2018", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiamustanggt"] = { ['name'] = "Mustang GT", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiacapricesid"] = { ['name'] = "GM Caprice SID", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiaschaftersid"] = { ['name'] = "GM Schafter SID", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiasilverado"] = { ['name'] = "Chevrolet Silverado", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiatahoe"] = { ['name'] = "Chevrolet Tahoe", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiaexplorer"] = { ['name'] = "Ford Explorer", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiataurus"] = { ['name'] = "Ford Taurus", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiavictoria"] = { ['name'] = "Ford Victoria", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiabmwr1200"] = { ['name'] = "BMW R1200", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policiaheli"] = { ['name'] = "Policia Helicóptero", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["fbi2"] = { ['name'] = "Granger SOG", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["policeb"] = { ['name'] = "Harley Davidson", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["riot"] = { ['name'] = "Blindado", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["paramedicoambu"] = { ['name'] = "Ambulância", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["paramedicocharger2014"] = { ['name'] = "Dodge Charger 2014", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["paramedicoheli"] = { ['name'] = "Paramédico Helicóptero", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["20blazer2"] = { ['name'] = "Trail Blazer 2021 Policia", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["mercedespolicia"] = { ['name'] = "Mercedes-AMG C63 Policia", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["jeeppolicia"] = { ['name'] = "Jeep Policia", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["chevypolicia"] = { ['name'] = "Chevrolet Chevy Policia", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["xre2019"] = { ['name'] = "XRE Policia", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tug"] = { ['name'] = "Barco de Pescador", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["priustaxi"] = { ['name'] = "Taxi", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["pounder2"] = { ['name'] = "Caminhao", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false }, 
	["f450towtruk"] = { ['name'] = "F450 Da Mecânica", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false }, 
	["pranger"] = { ['name'] = "Pranger", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false }, 
	["paradise"] = { ['name'] = "Paradise", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["seasparrow"] = { ['name'] = "Paramédico Helicóptero Água", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["coach"] = { ['name'] = "Coach", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["bus"] = { ['name'] = "Ônibus", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["flatbed"] = { ['name'] = "Reboque", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["towtruck"] = { ['name'] = "Towtruck", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["towtruck2"] = { ['name'] = "Towtruck2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["rwnoader"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["rwnoader2"] = { ['name'] = "Rwnoader2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["rubble"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["taxi"] = { ['name'] = "Taxi", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["boxville4"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["trash2"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tiptruck"] = { ['name'] = "Tiptruck", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["scorcher"] = { ['name'] = "Scorcher", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tribike"] = { ['name'] = "Tribike", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tribike2"] = { ['name'] = "Tribike2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tribike3"] = { ['name'] = "Tribike3", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["fixter"] = { ['name'] = "Fixter", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["cruiser"] = { ['name'] = "Cruiser", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["bmx"] = { ['name'] = "Bmx", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["dinghy"] = { ['name'] = "Dinghy", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["jetmax"] = { ['name'] = "Jetmax", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["marquis"] = { ['name'] = "Marquis", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["seashark3"] = { ['name'] = "Seashark3", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["speeder"] = { ['name'] = "Speeder", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["speeder2"] = { ['name'] = "Speeder2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["squalo"] = { ['name'] = "Squalo", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["suntrap"] = { ['name'] = "Suntrap", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["toro"] = { ['name'] = "Toro", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["toro2"] = { ['name'] = "Toro2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tropic"] = { ['name'] = "Tropic", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tropic2"] = { ['name'] = "Tropic2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["phantom"] = { ['name'] = "Phantom", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["packer"] = { ['name'] = "Packer", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["supervolito"] = { ['name'] = "Supervolito", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["supervolito2"] = { ['name'] = "Supervolito2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["cuban800"] = { ['name'] = "Cuban800", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["mammatus"] = { ['name'] = "Mammatus", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["vestra"] = { ['name'] = "Vestra", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["velum2"] = { ['name'] = "Velum2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["buzzard2"] = { ['name'] = "Buzzard2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["frogger"] = { ['name'] = "Frogger", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["maverick"] = { ['name'] = "Maverick", ['price'] = 100000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tanker2"] = { ['name'] = "Gas", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["armytanker"] = { ['name'] = "Diesel", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tvtrailer"] = { ['name'] = "Show", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["trailerlogs"] = { ['name'] = "Woods", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tr4"] = { ['name'] = "Cars", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["speedo"] = { ['name'] = "Speedo", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["primo2"] = { ['name'] = "Primo2", ['price'] = 250000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["faction2"] = { ['name'] = "Faction2", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["chino2"] = { ['name'] = "Chino2", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tornado5"] = { ['name'] = "Tornado5", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["daemon"] = { ['name'] = "Daemon", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["sanctus"] = { ['name'] = "Sanctus", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["gburrito"] = { ['name'] = "GBurrito", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["slamvan2"] = { ['name'] = "Slamvan2", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["stafford"] = { ['name'] = "Stafford", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["cog55"] = { ['name'] = "Cog55", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["superd"] = { ['name'] = "Superd", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["btype"] = { ['name'] = "Btype", ['price'] = 200000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["tractor2"] = { ['name'] = "Tractor2", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["rebel"] = { ['name'] = "Rebel", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["flatbed3"] = { ['name'] = "flatbed3", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["cargobob2"] = { ['name'] = "Cargo Bob 2", ['price'] = 1000000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },		
	["av-nc7"] = { ['name'] = "Honda NX500", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["av-ghibli"] = { ['name'] = "Maserati Ghibi", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["police2"] = { ['name'] = "Porsche 718 Caymans", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["trans_mbxclass"] = { ['name'] = "Mercedes-Benz X-Class", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["av-levante"] = { ['name'] = "Maserati Levante", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["av-amarok"] = { ['name'] = "Amarok da Mecânica", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },
	["stockade"] = { ['name'] = "Carro Forte", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false }, 
	["av-m8"] = { ['name'] = "BMW M8", ['price'] = 1000, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false }, 
	["swift"] = { ['name'] = "Swift", ['price'] = 999999999, ['tipo'] = "work", ['modelo'] = "outros", ['mala'] = 25, ["banned"] = false },

	--CARROS VIP 1
	["audirs6"] = { ['name'] = "Audi RS6", ['price'] = 500000,['price2'] = 380, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["audirs7"] = { ['name'] = "Audi RS7", ['price'] = 500000,['price2'] = 450, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["bmwm3f80"] = { ['name'] = "BMW M3 F80", ['price'] = 500000,['price2'] = 460, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["lancerevolution9"] = { ['name'] = "Lancer Evolution 9", ['price'] = 500000,['price2'] = 490, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["nissan370z"] = { ['name'] = "Nissan 370Z", ['price'] = 500000,['price2'] = 600, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["nissanskyliner34"] = { ['name'] = "Nissan Skyline R34", ['price'] = 500000,['price2'] = 630, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["eclipse"] = { ['name'] = "Mitsubishi Eclipse", ['price'] = 500000,['price2'] = 400, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["amggtr"] = { ['name'] = "Mercedes AMG", ['price'] = 500000,['price2'] = 470, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["focusrs"] = { ['name'] = "Focus RS", ['price'] = 500000,['price2'] = 430, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["lancerevolutionx"] = { ['name'] = "Lancer Evolution X", ['price'] = 500000,['price2'] = 590, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["bme6tun"] = { ['name'] = "BMW M5", ['price'] = 500000,['price2'] = 510, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["18macan"] = { ['name'] = "Porsche Macan", ['price'] = 500000,['price2'] = 390, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["mazdarx7"] = { ['name'] = "Mazda RX7", ['price'] = 500000,['price2'] = 430, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["toyotasupra"] = { ['name'] = "Toyota Supra", ['price'] = 500000,['price2'] = 460, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },
	["teslaprior"] = { ['name'] = "Tesla Prior", ['price'] = 500000,['price2'] = 470, ['tipo'] = "carrosvip1", ['modelo'] = "outros", ['mala'] = 65 , ["banned"] = false },

	--CARROS VIP 2
	["dodgechargersrt"] = { ['name'] = "Dodge Charger SRT", ['price'] = 500000,['price2'] = 1120, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["bmwm4gts"] = { ['name'] = "BMW M4 GTS", ['price'] = 500000,['price2'] = 950, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["fordmustang"] = { ['name'] = "Ford Mustang", ['price'] = 500000,['price2'] = 1170, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["mercedesa45"] = { ['name'] = "Mercedes A45", ['price'] = 500000,['price2'] = 990, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["mustangmach1"] = { ['name'] = "Mustang Mach 1", ['price'] = 500000,['price2'] = 1030, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["nissangtr"] = { ['name'] = "Nissan GTR", ['price'] = 500000,['price2'] = 1140, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["70camarofn"] = { ['name'] = "camaro Z28 1970", ['price'] = 500000,['price2'] = 1040, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["g65amg"] = { ['name'] = "Mercedes G65", ['price'] = 500000,['price2'] = 870, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["m6e63"] = { ['name'] = "BMW M6 E63", ['price'] = 500000,['price2'] = 1050, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["fc15"] = { ['name'] = "Ferrari California", ['price'] = 500000,['price2'] = 1180, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["71gtx"] = { ['name'] = "Plymouth 71 GTX", ['price'] = 500000,['price2'] = 880, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["19ftype"] = { ['name'] = "Jaguar F-Type", ['price'] = 500000,['price2'] = 930, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["s15"] = { ['name'] = "Nissan Silvia S15", ['price'] = 500000,['price2'] = 890, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["bc"] = { ['name'] = "Pagani Huayra", ['price'] = 500000,['price2'] = 1090, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["palameila"] = { ['name'] = "Porsche Panamera", ['price'] = 500000,['price2'] = 1020, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["hondafk8"] = { ['name'] = "Honda FK8", ['price'] = 500000,['price2'] = 1100, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["porsche930"] = { ['name'] = "Porsche 930", ['price'] = 500000,['price2'] = 920, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["2018zl1"] = { ['name'] = "Camaro ZL1", ['price'] = 500000,['price2'] = 1160, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["filthynsx"] = { ['name'] = "Honda NSX", ['price'] = 500000,['price2'] = 1150, ['tipo'] = "carrosvip2", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },

	--CARROS VIP 3
	["ferrariitalia"] = { ['name'] = "Ferrari Italia 478", ['price'] = 500000,['price2'] = 1850, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["rmodamgc63"] = { ['name'] = "Mercedes AMG C63", ['price'] = 500000,['price2'] = 1480, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["veneno"] = { ['name'] = "Lamborghini Veneno", ['price'] = 500000,['price2'] = 1890, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["p1"] = { ['name'] = "Mclaren P1", ['price'] = 500000,['price2'] = 1930, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["488gtb"] = { ['name'] = "Ferrari 488 GTB", ['price'] = 500000,['price2'] = 1780, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["911r"] = { ['name'] = "Porsche 911R", ['price'] = 500000,['price2'] = 1950, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["i8"] = { ['name'] = "BMW i8", ['price'] = 500000,['price2'] = 1640, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["fxxkevo"] = { ['name'] = "Ferrari FXXK Evo", ['price'] = 500000,['price2'] = 2000, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["lp700r"] = { ['name'] = "Lamborghini LP700R", ['price'] = 500000,['price2'] = 1740, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["agerars"] = { ['name'] = "Koenigsegg Agera RS", ['price'] = 1000000,['price2'] = 2000, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["180sx"] = { ['name'] = "Nissan 180SX", ['price'] = 500000,['price2'] = 1530, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["amarok"] = { ['name'] = "VW Amarok", ['price'] = 500000,['price2'] = 1480, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["defiant"] = { ['name'] = "AMC Javelin 72", ['price'] = 500000,['price2'] = 1430, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["eleanor"] = { ['name'] = "Mustang Eleanor", ['price'] = 500000,['price2'] = 1500, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["slsamg"] = { ['name'] = "Mercedes SLS", ['price'] = 500000,['price2'] = 1570, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["urus2018"] = { ['name'] = "Lamborghini Urus 2018", ['price'] = 500000,['price2'] = 1450, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["nissantitan17"] = { ['name'] = "Nissan Titan 2017", ['price'] = 500000,['price2'] = 3050, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },
	["porsche992"] = { ['name'] = "Porsche 992", ['price'] = 500000,['price2'] = 1690, ['tipo'] = "carrosvip3", ['modelo'] = "outros", ['mala'] = 75 , ["banned"] = false },

	-- MOTOS VIP
	["africat"] = { ['name'] = "Honda CRF 1000", ['price'] = 500000,['price2'] = 1630, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["r1250"] = { ['name'] = "BMW R1250", ['price'] = 500000,['price2'] = 1980, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["mt03"] = { ['name'] = "Yamaha MT-03", ['price'] = 500000,['price2'] = 620, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["500x"] = { ['name'] = "Honda CB 500 X", ['price'] = 500000,['price2'] = 1030, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["cb500f"] = { ['name'] = "CB500F 2020", ['price'] = 500000,['price2'] = 1100, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["hornet"] = { ['name'] = "Honda Cb600f", ['price'] = 500000,['price2'] = 1640, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["fz07"] = { ['name'] = "Yamaha MT-07", ['price'] = 500000,['price2'] = 1720,  ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["cb650r"] = { ['name'] = "HONDA CB650R 2021", ['price'] = 500000,['price2'] = 1700, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["yzfr6"] = { ['name'] = "Yamaha R6", ['price'] = 500000,['price2'] = 1930, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["hvrod"] = { ['name'] = "Harley-Davidson", ['price'] = 500000,['price2'] = 1520, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["z1000"] = { ['name'] = "Kawasaki Z1000", ['price'] = 500000,['price2'] = 2030, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["sxr"] = { ['name'] = "BMW 1000r SXR", ['price'] = 500000,['price2'] = 2100, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["zx10"] = { ['name'] = "Kawasaki Ninja ZX 10", ['price'] = 500000,['price2'] = 2540, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	["nh2r"] = { ['name'] = "Kawasaki Ninja H2 R", ['price'] = 500000,['price2'] = 3050, ['tipo'] = "motosvip", ['modelo'] = "outros", ['mala'] = 50 , ["banned"] = false },
	
	--EXCLUSIVE 
	["cargobob"] = { ['name'] = "Cargo Bob", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["havok"] = { ['name'] = "Havok", ['price'] = 999999999, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["swift2"] = { ['name'] = "Swift2", ['price'] = 999999999, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["volatus"] = { ['name'] = "Volatus", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },	
	["raptor2017"] = { ['name'] = "Ford Raptor 2017", ['price'] = 500000,['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["lamborghinihuracan"] = { ['name'] = "Lamborghini Huracan", ['price'] = 500000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["tractor"] = { ['name'] = "Tractor", ['price'] = 9999999999, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },	
	["Y1700MAX"] = { ['name'] = "Yamaha 1700 V-MAX", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["goldwing"] = { ['name'] = "Honda GoldWing 1800", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["nissangtrnismo"] = { ['name'] = "Nissan GTR Nismo", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["m2"] = { ['name'] = "BMW M2", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["aperta"] = { ['name'] = "La Ferrari", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bettle"] = { ['name'] = "New Bettle", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["senna"] = { ['name'] = "Mclaren Senna", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["rmodx6"] = { ['name'] = "BMW X6", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bnteam"] = { ['name'] = "Bentley", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["rmodlp770"] = { ['name'] = "Lamborghini Centenario", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["divo"] = { ['name'] = "Buggati Divo", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["lamtmc"] = { ['name'] = "Lamborghini Terzo", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["vantage"] = { ['name'] = "Aston Martin Vantage", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["urus"] = { ['name'] = "Lamborghini Urus", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["celta"] = { ['name'] = "Celta Paredão", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["rsvr16"] = { ['name'] = "Ranger Rover", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["f4rr"] = { ['name'] = "Augusta", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["db11"] = { ['name'] = "Aston Martin DB11", ['price'] = 500000,['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["rcbandito"] = { ['name'] = "RC", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["ghispo3"] = { ['name'] = "Ghispo Xeriff", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["r1custom"] = { ['name'] = "R1 Xeriff", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["polsrt10"] = { ['name'] = "Xeriff SRT10", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["tr22"] = { ['name'] = "Tesla", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["kuruma2"] = { ['name'] = "Kuruma do Torres", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["18jeep"] = { ['name'] = "Jeep Xerife", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["polgt500"] = { ['name'] = "GT 500 Xerife", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["17raptorpd"] = { ['name'] = "Raptor 17 Xerife", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["can"] = { ['name'] = "Can", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["cam8tun"] = { ['name'] = "Toyota XSE", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bmws"] = { ['name'] = "Augusta", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["ghispo2"] = { ['name'] = "Maserati", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["polgs350"] = { ['name'] = "GS350", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bmpos8"] = { ['name'] = "BMW OS8", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["z419"] = { ['name'] = "BMW Z4", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["r8ppi"] = { ['name'] = "Audi R8", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["zondar"] = { ['name'] = "Pagani Zonda R", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["sspres"] = { ['name'] = "Suburban", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["laferrari17"] = { ['name'] = "LaFerrari", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["2020silv"] = { ['name'] = "Silverado2020", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["19ramdonk"] = { ['name'] = "Dodge Ram Donk", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["silv86"] = { ['name'] = "Silverado Donk", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["ninjah2"] = { ['name'] = "Ninja H2", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["regera"] = { ['name'] = "Koenigsegg Regera", ['price'] = 500000,['price2'] = 300, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["msohs"] = { ['name'] = "Mclaren 688 HS", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["gt17"] = { ['name'] = "Ford GT 17", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bbentayga"] = { ['name'] = "Bentley Bentayga", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["trr"] = { ['name'] = "KTM TRR", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bmws"] = { ['name'] = "BMW S1000", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["hcbr17"] = { ['name'] = "Honda CBR17", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["f12tdf"] = { ['name'] = "Ferrari F12 TDF", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["lykan"] = { ['name'] = "Plymouth 71 GTX", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["SVR14"] = { ['name'] = "Ranger Rover", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["evoque"] = { ['name'] = "Ranger Rover Evoque", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["Bimota"] = { ['name'] = "Ducati Bimota", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["20r1"] = { ['name'] = "Yamaha YZF R1", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["yzfr125"] = { ['name'] = "Yamaha YZF R125", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["pistas"] = { ['name'] = "Ferrari Pista", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bobbes2"] = { ['name'] = "Harley D. Bobber S", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["bobber"] = { ['name'] = "Harley D. Bobber ", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },
	["911tbs"] = { ['name'] = "Porsche 911S", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["rc"] = { ['name'] = "KTM RC", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },			
	["fox600lt"] = { ['name'] = "McLaren 600LT", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxbent1"] = { ['name'] = "Bentley Liter 1931", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxevo"] = { ['name'] = "Lamborghini EVO", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["jeepg"] = { ['name'] = "Jeep Gladiator", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxharley1"] = { ['name'] = "Harley-Davidson Softail F.B.", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxharley2"] = { ['name'] = "2016 Harley-Davidson Road Glide", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxleggera"] = { ['name'] = "Aston Martin Leggera", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxrossa"] = { ['name'] = "Ferrari Rossa", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxshelby"] = { ['name'] = "Ford Shelby GT500", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxsian"] = { ['name'] = "Lamborghini Sian", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxsterrato"] = { ['name'] = "Lamborghini Sterrato", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["foxsupra"] = { ['name'] = "Toyota Supra", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["m6x6"] = { ['name'] = "Mercedes Benz 6x6", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },	
	["faction2"] = { ['name'] = "Faction2", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["m6gt3"] = { ['name'] = "BMW M6 GT3", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50, ["banned"] = false },		
	["w900"] = { ['name'] = "Kenworth W900", ['price'] = 1000000, ['tipo'] = "exclusive", ['modelo'] = "esportivo", ['mala'] = 50 }		
}

return cfg